name: Build Docker Images for OpenCV Versions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opencv_version: 
          # OpenCV_4 versions
          - 4.0.0
          - 4.1.0
          - 4.1.1
          - 4.1.2
          # OpenCV_3 versions
          - 3.1.0
          - 3.4.0
          - 3.4.1
          - 3.4.2
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.opencv_version }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Image for OpenCV ${{ matrix.opencv_version }}
      run: |
        docker buildx build \
          --build-arg OPENCV_VERSION=${{ matrix.opencv_version }} \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new \
          --file opencv_3/3.1.0/Dockerfile \  # Path to Dockerfile
          --tag raspberrypi3-opencv:${{ matrix.opencv_version }} \
          --load \
          opencv_3/3.1.0  # Build context (folder containing Dockerfile)

    - name: Save Cache
      if: always()
      run: |
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
